# app detail
site-name: "Flet Web Material"
repo-url: "https://github.com/LineIndent"

# app theme
theme:
  - bgcolor: "#2e2f3e"
  - primary: "red"
  - accent: "blue300"

# navigation tree
nav:
  - Home: "index.py"
  - About: "about.py"
